---
- name: generate openstack in-memory inventory 
  hosts: jumpbox
  gather_facts: false

  tasks:

    - name: Fetch Instance Info
      os_server_facts:
        cloud: ospcloud
        region_name: RegionOne
      register: result

    - name: Display facts  
      debug:
        var: result | to_nice_json
        verbosity: 2

    - name: Add host
      add_host:
        name: "{{ item.public_v4 }}"
        group:
          - "{{ item.metadata.group }}"
          - "{{ item.metadata.deployment_name }}"
      loop: "{{ result.ansible_facts.openstack_servers }}"

    - name: Generate lab static inventory file
      template:
        src: lab_inventory.j2
        dest: "/tmp/my_inventory"
      delegate_to: localhost

    - name: print hosts
      debug:
        msg:
          - "name: {{ item.public_v4 }}"
          - "group: {{ item.metadata.group }}"
      loop: "{{ result.ansible_facts.openstack_servers }}"
