- name: Run common setup
  import_playbook: playbooks/common.yml

- name: Install and configure frontend
  import_playbook: playbooks/front_end.yml
 
- name: Install and configure app_tier
  import_playbook: playbooks/app_tier.yml

- name: Install database tier
  hosts: appdbs
  tags:
    - dbs
    - postgres

  roles:
    - geerlingguy.postgresql

