---
- name: Generate openstack in-memory inventory 
  hosts: jumpbox
  gather_facts: false

  roles:
    - name: osp-inventory

# Setup front-end load balancer tier

- name: Setup frontend load-balancer tier
  hosts: frontends
  gather_facts: false
  become: yes
  tags:
    - frontends

  roles:
    - common
    - frontend-tier

# Setup application servers tier

- name: Setup app tier
  hosts: apps
  gather_facts: false
  #become: yes
  tags:
    - apps

  roles:
    - common
    - app-tier

# Setup database tier

- name: Setup database tier
  hosts: appdbs
  #become: yes
  tags:
    - databases

  roles:
    - common
    - geerlingguy.postgresql

